version: "2"   
services:  
  web:  
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/nginx 
    container_name: web_fecshop 
    ports:  
      - "81:80" 
    restart: always
    volumes:  
      - ./app:/www/web
      - ./services/web/nginx/conf:/etc/nginx
      - ./services/web/nginx/logs:/www/web_logs
    networks:
        - code-network
    depends_on:
      - php
  mysql:  
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/mysql 
    container_name: mysql_fecshop
    ports:  
      - "3307:3306"
    restart: always
    volumes:  
      - ./db/mysql/data:/var/lib/mysql 
      - ./db/mysql/example_db:/var/example_db 
      - ./db/mysql/conf.d:/etc/mysql/conf.d      
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fecshop
    networks:
      - code-network 
  node:
    image: haohonglong/node:1.0
    container_name: node_fecshop
    ports:
      - 4201:4200
      - 3031:3000
      - 3032:8080
    volumes:
      - ./app:/www
    working_dir: /www
    command: top
    networks:
      - code-network  
    tty: true
  php:  
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/php-7.1.13-fpm_2
    container_name: php_fecshop
    restart: always
    volumes:  
      - ./app:/www/web
      - ./services/php/etc/php7.1.13.ini:/usr/local/etc/php/conf.d/php7.1.13.ini
    depends_on:
      - mongodb
      - mysql
    networks:
        - code-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_fecshop
    ports:
        - "8081:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    #volumes:
      #- "./app/phpmyadmin:/var/www/html"
    depends_on:
        - mysql
    networks:
        - code-network
  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/mongo
    container_name: mongodb_fecshop
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./db/mongodb/data:/data/db
      - ./db/mongodb/example_db:/data/example_db
      - ./db/mongodb/logs:/data/logs
    networks:
      - code-network 
  
  xunsearch:
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/xunsearch
    container_name: xunsearch_fecshop
    restart: always
    volumes:
      - ./db/xunsearch/data:/usr/local/xunsearch/data  
    networks:
      - code-network 
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/fecshopsoft/redis
    container_name: redis_fecshop
    restart: always
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    volumes:
      - ./db/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf 
      - ./db/redis/data:/data 
      - ./db/redis/etc/redis-password:/run/secrets/redis-password 
    networks:
      - code-network 
networks:
  code-network:
    driver: bridge
        
        
        
        
        
